# Generated by Django 5.2.1 on 2025-05-24 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='New_Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('resume_file', models.FileField(upload_to='uploads/resumes')),
                ('image_file', models.ImageField(upload_to='uploads/photos')),
            ],
        ),
    ]
